### ISSUE TITLE
The blog isn't visible (Help for quickinstall)

### ISSUE THREAD

**Issue by aspiess** [fnagel/t3extblog#173]
Hello,

I think I need some help with the installation of the t3extblog extension. I've done all installation steps, but I can't see the blog on my main-page.

I've created a new template for the blog, contains the static template "T3Extblog: Default setup". Afterwards  the following pages was created:
![qinstall_help1](https://cloud.githubusercontent.com/assets/2042934/26629660/a3dd5e52-4603-11e7-828a-00d37287f483.jpg)

All pages containing the plugins needed and the folder "data" is my storage for posts. The template "Blog" has the following settings:
![qinstall_help2](https://cloud.githubusercontent.com/assets/2042934/26629705/db7621fa-4603-11e7-98f0-9d98b4eb0b9d.jpg)

Did I done everything right? Thanks in advance.
Greetings, Arne

**Comment by fnagel** [comment]
You need to setup the plugins 1) and add some proper config for your templating 2). Using your `page` configuration you will always see `Hello World`. Please note that page templating in more like a general TYPO3 topic.

1) See Section 4: https://docs.typo3.org/typo3cms/extensions/t3extblog/Installation/Full.html

2) State of the art page rendering would be using Fluidtemplating, see:  https://wiki.typo3.org/T3Doc/Fluidtemplate_by_example

You might want to start with an introduction package of TYPO3 instead of a blank project: https://docs.typo3.org/typo3cms/GettingStartedTutorial/Installation/Index.html

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
@aspiess Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
