### ISSUE TITLE
Render inline extbase plugin

### ISSUE THREAD

**Issue by dablach** [fnagel/t3extblog#189]
When rendering inline content elements that are Extbase plugins, the framework configuration gets lost (overwritten). In my case, a dce element was rendered, which resultet in a persistence.storagePid of 0. Because of that the number of comments (queried in Post::initComments) was always zero (list action).

I could fix this by storing and restoring the framework configuration in ViewHelpers\Frontend\RenderContentViewHelper like that (around line 111):

```
$configurationManager = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\ObjectManager::class)->get(\TYPO3\CMS\Extbase\Configuration\ConfigurationManager::class);
$frameworkConfiguration = $configurationManager->getConfiguration(\TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface::CONFIGURATION_TYPE_FRAMEWORK);

$html = $this->getContentObjectRenderer()->cObjGetSingle('RECORDS', $configuration);

$configurationManager->setConfiguration($frameworkConfiguration);
```

**Comment by fnagel** [comment]
Please add info as described in https://github.com/fnagel/t3extblog/blob/master/CONTRIBUTING.md
Please add info about used DCE version as well.

#185 This seems not to be true for extbase plugins in general but for EXT:dce (and other?) as I'm running multiple extbase plugins within the t3extblog CEs without issues.

The `renderRecord` method is taken from VHS. Would you mind testing if this issue occues when using their VH too? Would be helpful for a better understanding what might be the issue here.

See https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Content/AbstractContentViewHelper.php

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
