### ISSUE TITLE
Support for PHP 7.3 and PHP 7.4

### ISSUE THREAD

**Issue by tomhatzer** [fnagel/t3extblog#224]
Hi Felix,

I'd love to use t3extblog with php 7.3 and 7.4 as php 7.2 only has security support right now until Nov 2020.
Do you know of any problems with PHP 7.3 or PHP 7.4 yet? I'm currently upgrading a Typo3 8.7 project to Typo3 9.5 and would like to use the latest php version with it.

Thank you very much and best wishes
Tom

**Comment by fnagel** [comment]
Hey Tom, 

no, there are no issues I'm aware of and I don't expect problems. I tend to adjust my extension dependency constraints on what I've tested and I did not find time to test with PHP 7.3. or 7.4.
You probably should just give it a try (if you're using composer you might need to clone it and change the constraints) -- I assume it will work without issues. 

Please give feedback if it works, because I will release a 5.1.0 soon with lots of bugfixes, improvements and even a few new features (TWBS 4 support, new logging, ...). A version for 10.x is in the making too!

Yours
Felix

**Comment by tomhatzer** [comment]
Hey Felix,

thanks for your reply. I've been running the current versions with PHP 7.3 for quite some time now and didn't have any problems. For PHP 7.4 there seem to be a few warnings, I'll see if I can come up with a PR for them.
Would be great if we could add at least PHP 7.3 to the compatible versions. I'll do my best to get PHP 7.4 compatibility in it too.

Have a great evening/night.

Tom

**Comment by fnagel** [comment]
> I've been running the current versions with PHP 7.3 for quite some time now and didn't have any problems.

Sounds good. I will push an update soon. Will be included in 5.1.0!

> I'll do my best to get PHP 7.4 compatibility in it too.

That would be great! Just ping me here!

**Comment by fnagel** [comment]
@tomhatzer I need to do a small bugfix release for 6.x soon. Any feedback on PHP 7.4 compatibility? Would be a nice add-on to a 6.0.1 release...

**Comment by tomhatzer** [comment]
@fnagel sorry for not replying earlier. I didn't update to PHP 7.4, I'm still running on PHP 7.3 at the moment. The update to 7.4 will be done somewhere at the end of the year.
With 7.3 there's no problem at the moment with the 2.4.x version. I've got a bug with the 2.5.2 though that I'll have to look into.
