### ISSUE TITLE
Unable to configure page in typo3 10.4.6

### ISSUE THREAD

**Issue by Himakar-PV** [fnagel/t3extblog#237]
When I try to configure with v10.4.6 it throws page not configured error as shown below:
![image](https://user-images.githubusercontent.com/59556885/91533410-076a3f80-e93a-11ea-9fa0-0855ba7d26fd.png)

This is the configuration I made in template:

![image](https://user-images.githubusercontent.com/59556885/91533548-47312700-e93a-11ea-9ee0-f79446f4498b.png)

![image](https://user-images.githubusercontent.com/59556885/91533883-d5a5a880-e93a-11ea-9c4a-210c021330bd.png)

![image](https://user-images.githubusercontent.com/59556885/91533920-e2c29780-e93a-11ea-9c23-41314e8885bf.png)

In log file I observed this:
[ERROR] request="c1aeaa4b136a4" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"page | module = t3blog"}

**Comment by Himakar-PV** [comment]
I fixed page rendering issue, I wonder why it is not explained in the docs which is very important.

Below content need to be added in the Setup of template

![image](https://user-images.githubusercontent.com/59556885/91548295-61c1cb00-e94f-11ea-9de0-c8ad454f8019.png)

Still I see below error in log file:

[ERROR] request="c1aeaa4b136a4" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"page | module = t3blog"}

**Comment by fnagel** [comment]
Hey! Mmhh, that looks like a couple of issues:

* Your initial error message has nothing to do with t3extblog but with missing page configuration. Please see general TYPO3 CMS docs
* Your page structure looks odd. Why having multiple "Blog" pages and storages? What page type is the first "Blog" page?

> I fixed page rendering issue, I wonder why it is not explained in the docs which is very important.

The docs cover everything regarding the extension, not TYPO3 CMS basics. You need a working TYPO3 instance in order to work with extensions.

> Expression could not be parsed

Looks like there is an outdated condition in place. Would you mind testing if changing the following line helps:

`[page | module = t3blog]`

to 

`[page["module"] == "t3blog"]`

in https://github.com/fnagel/t3extblog/blob/master/Configuration/TSconfig/Page.tsconfig#L11

**Comment by Himakar-PV** [comment]
Thank you @fnagel , your suggestion in Page.tsconfig worked.

#Your page structure looks odd. Why having multiple "Blog" pages and storages? What page type is the first "Blog" page?

In my first image, I was checking to use blog extension out of my custom extension and inside my custom extension. "Home" page is linked with custom extension.

**Comment by fnagel** [comment]
> your suggestion in Page.tsconfig worked.

Nice! Thanks for the feedback. Will be included in the next release!
