### ISSUE TITLE
Update default HTML layout to match Twitter Bootstrap 3.x

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#24]
Update templates and partials to match Twitter Bootstrap 3.x instead of 2.3.x

**Comment by m4chi** [comment]
Hi Felix, are you still working on this one?

**Comment by fnagel** [comment]
Planned as I want to change my website to use Bootstrap 3 but I'm not sure how long it will take until I gather enough time to do so. 

Anyway, help and PRs are welcome!

**Comment by m4chi** [comment]
At them moment, I have the same problem and in general would likely mess up your extension rather than improve it… I’m pretty much new to typo3, typoscript and the github platform, for that matter. However, I will try to make some adjustments in the templates and am happy to send them over for your consideration...


Am 02.05.2015 um 11:56 schrieb Felix Nagel <notifications@github.com>:

**Comment by fnagel** [comment]
For most changes (all?) you won't need TYPO3 or TS knowledge in specific as 95% of the changes need to be done in the HTML Templates and Partials. 

I'm fine with sending a zip or something. No problem to create a branch out of that and discuss your changes here on Github in a PR.

So, if you need to adjust the templates for your project anyway I would appreciate sharing them.

**Comment by m4chi** [comment]
will do! hopefully I can get there soon.
a major issue at the moment is that the comment layout is somewhat messed up (http://home.uni-leipzig.de/~jgames/index.php?id=47) and I will have to do something at least to get the form input fields styled...

Am 02.05.2015 um 12:04 schrieb Felix Nagel <notifications@github.com>:

**Comment by fnagel** [comment]
Anyone got some work done here?

**Comment by fnagel** [comment]
New PR: #77
