### ISSUE TITLE
List page can render detail view/single blog post with default routing configuration when using separate pages for list/detail

### ISSUE THREAD

**Issue by fgerards** [fnagel/t3extblog#253]
I noticed, that the list page can also render single post with the default shipped routing configuration. This is normally no problem, but if some editor publishes a link without the url-segment for the detail view page, this leads to duplicate content.

Solution: If separate list and detail/show pages are used, the routing configuration should be split and the configurations should be limited to the corresponding pages. another solution would be a canonical tag generator, which points any url containing a post-title on the list page to the detail page.

The aim is to be "bullet-proof" seo-wise. Which solution would you prefer ?

**Comment by fnagel** [comment]
I'm not sure if I understand the issue here. The "blogsystem" Plugin manages both, the list and the detail views. That is on purpose and shouldn't be an issue SEO wise. 

Can you explain to me when this could lead to duplicate content? Maybe with an example URL? I've tried to reproduce this with my own page but wasn't able to reproduce the issue:

- https://www.felixnagel.com/blog/ (list)
- https://www.felixnagel.com/blog/artikel/2022/05/18/typo3-t3extblog-700-released/ (detail)
- https://www.felixnagel.com/blog/2022/05/18/typo3-t3extblog-700-released/ (invalid example -> produces 404)
- https://www.felixnagel.com/blog/artikel/typo3-t3extblog-700-released/ (invalid example -> produces 404)
- https://www.felixnagel.com/blog/typo3-t3extblog-700-released/ (invalid example -> produces 404)

I would prefer not to change the plugin structure as this is a breaking change. But creating a canonical tag generator seems like a good idea anyway, but afaics there is a proper canonical tag rendered for each detail page.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
